runtime: python310
service: dsmpl-backend
entrypoint: gunicorn -w 4 -b :$PORT config.wsgi:application

handlers:
- url: /.*
  script: auto

runtime_config:
    operating_system: "ubuntu22.04"
    runtime_version: "3.10"

instance_class: F1
automatic_scaling:
  min_instances: 0
  max_instances: 1
