# Generated by Django 4.2.4 on 2023-08-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Guests",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("visitor_name", models.CharField(max_length=255)),
                ("employee_name", models.CharField(max_length=255)),
                ("relationship", models.CharField(max_length=255)),
                ("in_time", models.DateTimeField(auto_now_add=True)),
                ("out_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
