# Generated by Django 4.2.4 on 2023-08-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("milkmil", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Milk",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("type", models.CharField(max_length=255)),
                ("quantity", models.FloatField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
