# Generated by Django 4.2.4 on 2023-08-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("milkmil", "0002_milk"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("type", models.CharField(max_length=255)),
                ("driver_name", models.CharField(max_length=255)),
                ("reason", models.CharField(max_length=255)),
                ("num_passengers", models.IntegerField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("in_time", models.DateTimeField(auto_now_add=True)),
                ("out_time", models.DateTimeField(blank=True, null=True)),
                ("out_kms", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
