# Generated by Django 4.2.4 on 2023-08-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("milkmil", "0003_vehicle"),
    ]

    operations = [
        migrations.CreateModel(
            name="Keys",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "key_type",
                    models.CharField(
                        choices=[
                            ("SPINNING", "SPINNING"),
                            ("CARDING", "CARDING"),
                            ("AUTOCONER", "AUTOCONER"),
                            ("NEW GODOWN", "NEW GODOWN"),
                            ("CANTEEN", "CANTEEN"),
                            ("COMBER", "COMBER"),
                            ("FM ROOM", "FM ROOM"),
                            ("OFFICE", "OFFICE"),
                            ("SIMPLEX", "SIMPLEX"),
                            ("STORE ROOM", "STORE ROOM"),
                        ]
                    ),
                ),
                ("taken_time", models.DateTimeField(auto_now_add=True)),
                ("returned_time", models.DateTimeField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
