# Generated by Django 4.2.4 on 2023-08-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("milkmil", "0006_masterdata"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialOutward",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField(auto_now_add=True)),
                ("time", models.TimeField(auto_now_add=True)),
                ("invoice_num", models.CharField()),
                (
                    "status",
                    models.CharField(
                        choices=[("QUEUE", "QUEUE"), ("DISPATCHED / COMPLETED", "DISPATCHED / COMPLETED")]
                    ),
                ),
            ],
        ),
    ]
