# Generated by Django 4.2.4 on 2023-08-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("milkmil", "0009_remove_keys_timestamp_remove_milk_timestamp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="milk",
            name="quantity",
            field=models.IntegerField(),
        ),
    ]
