# Generated by Django 4.2.4 on 2023-08-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("milkmil", "0010_alter_milk_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guests",
            name="out_date",
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="guests",
            name="out_time",
            field=models.TimeField(default=None, null=True),
        ),
    ]
