# Generated by Django 4.2.4 on 2023-08-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("milkmil", "0012_alter_materialoutward_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="returnablematerials",
            name="status",
            field=models.CharField(
                choices=[
                    ("YET TO BE RETURNED", "YET TO BE RETURNED"),
                    ("RETURNED / COMPLETED", "RETURNED / COMPLETED"),
                ],
                default="YET TO BE RETURNED",
            ),
        ),
    ]
