# Generated by Django 4.2.4 on 2023-08-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("milkmil", "0013_alter_returnablematerials_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="guests",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/guests/"),
        ),
    ]
