# Generated by Django 4.2.4 on 2023-08-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("milkmil", "0016_alter_guests_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialinward",
            name="image",
            field=models.TextField(blank=True, null=True),
        ),
    ]
