# Generated by Django 4.2.4 on 2023-08-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("milkmil", "0019_alter_barcode_barcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="barcode",
            name="invoice_num",
            field=models.CharField(),
        ),
    ]
