# Generated by Django 4.2.4 on 2023-08-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("milkmil", "0020_alter_barcode_invoice_num"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keys",
            name="key_type",
            field=models.CharField(
                choices=[
                    ("SMALL GATE KEY", "SMALL GATE KEY"),
                    ("MAIN GATE KEY", "MAIN GATE KEY"),
                    ("GIRLS HOSTEL GATE KEY", "GIRLS HOSTEL GATE KEY"),
                    ("SIMPLEX KEY", "SIMPLEX KEY "),
                    ("STORES KEY", "STORES KEY"),
                    ("COMBER KEY", "COMBER KEY"),
                    ("CARDING KEY", "CARDING KEY"),
                    ("SPINNING KEY", "SPINNING KEY"),
                    ("AUTO CONER", "AUTO CONER"),
                    ("CANTEEN KEY", "CANTEEN KEY"),
                ]
            ),
        ),
    ]
