# Generated by Django 4.2.4 on 2023-08-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("milkmil", "0023_alter_keysmaster_key_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employees",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("role", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=255)),
            ],
        ),
    ]
