# Generated by Django 4.2.4 on 2023-08-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("milkmil", "0024_employees"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keys",
            name="key_type",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="keysmaster",
            name="key_type",
            field=models.CharField(),
        ),
    ]
