# Generated by Django 4.2.4 on 2023-08-22 15:07

from django.db import migrations
import milkmil.models


class Migration(migrations.Migration):
    dependencies = [
        ("milkmil", "0027_alter_guests_out_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guests",
            name="in_time",
            field=milkmil.models.TimeFieldWithoutMicroseconds(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="guests",
            name="out_time",
            field=milkmil.models.TimeFieldWithoutMicroseconds(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="keys",
            name="returned_time",
            field=milkmil.models.TimeFieldWithoutMicroseconds(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="keys",
            name="taken_time",
            field=milkmil.models.TimeFieldWithoutMicroseconds(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="materialinward",
            name="in_time",
            field=milkmil.models.TimeFieldWithoutMicroseconds(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="materialinward",
            name="out_time",
            field=milkmil.models.TimeFieldWithoutMicroseconds(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="materialoutward",
            name="time",
            field=milkmil.models.TimeFieldWithoutMicroseconds(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="milk",
            name="time",
            field=milkmil.models.TimeFieldWithoutMicroseconds(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="returnablematerials",
            name="in_time",
            field=milkmil.models.TimeFieldWithoutMicroseconds(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="returnablematerials",
            name="out_time",
            field=milkmil.models.TimeFieldWithoutMicroseconds(auto_now_add=True),
        ),
    ]
