# Generated by Django 4.2.4 on 2023-08-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("milkmil", "0029_alter_guests_in_time_alter_guests_out_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guests",
            name="in_time",
            field=models.TimeField(),
        ),
    ]
