# Generated by Django 4.2.4 on 2023-08-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("milkmil", "0031_alter_guests_in_date_alter_guests_in_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guests",
            name="in_date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="guests",
            name="in_time",
            field=models.TimeField(default=None, null=True),
        ),
    ]
