# Generated by Django 4.2.4 on 2023-08-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("milkmil", "0033_alter_guests_in_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="keys",
            name="person_name",
        ),
        migrations.AddField(
            model_name="keys",
            name="person_image",
            field=models.TextField(blank=True, null=True),
        ),
    ]
