# Generated by Django 4.2.4 on 2023-08-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("milkmil", "0034_remove_keys_person_name_keys_person_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="barcode",
            name="barcode",
            field=models.TextField(blank=True, null=True),
        ),
    ]
