# Generated by Django 4.2.4 on 2023-08-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("milkmil", "0035_alter_barcode_barcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialinward",
            name="type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
