# Generated by Django 4.2.4 on 2023-08-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("milkmil", "0036_materialinward_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="returnablematerials",
            name="gate_pass_num",
            field=models.CharField(max_length=255),
        ),
    ]
