# Generated by Django 4.2.4 on 2023-08-24 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("milkmil", "0037_alter_returnablematerials_gate_pass_num"),
    ]

    operations = [
        migrations.AlterField(
            model_name="returnablematerials",
            name="in_time",
            field=models.TimeField(
                auto_now_add=True,
                default=datetime.datetime(2023, 8, 24, 18, 5, 14, 844474, tzinfo=datetime.timezone.utc),
            ),
            preserve_default=False,
        ),
    ]
