# Generated by Django 4.2.4 on 2023-08-24 19:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("milkmil", "0038_alter_returnablematerials_in_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="returnablematerials",
            name="in_date",
            field=models.DateField(
                auto_now_add=True,
                default=datetime.datetime(2023, 8, 24, 19, 31, 49, 164874, tzinfo=datetime.timezone.utc),
            ),
            preserve_default=False,
        ),
    ]
