# Generated by Django 4.2.4 on 2023-08-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("milkmil", "0039_alter_returnablematerials_in_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="returnablematerials",
            name="out_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="returnablematerials",
            name="out_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
