# Generated by Django 4.2.4 on 2023-09-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("milkmil", "0040_alter_returnablematerials_out_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="barcode",
            name="test_report_num",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="barcode",
            name="invoice_num",
            field=models.CharField(max_length=255),
        ),
    ]
