# Generated by Django 4.2.4 on 2023-09-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("milkmil", "0041_barcode_test_report_num_alter_barcode_invoice_num"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialoutward",
            name="test_report_num",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="materialoutward",
            name="invoice_num",
            field=models.CharField(max_length=255),
        ),
    ]
