# Generated by Django 4.2.4 on 2023-09-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("milkmil", "0043_rename_reason_vehicle_vehicle_num_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vehicle",
            old_name="in_time",
            new_name="time",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="out_time",
        ),
        migrations.AddField(
            model_name="vehicle",
            name="status",
            field=models.CharField(blank=True, choices=[("IN", "IN"), ("OUT", "OUT")], null=True),
        ),
    ]
