# Generated by Django 4.2.4 on 2023-09-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("milkmil", "0044_rename_in_time_vehicle_time_remove_vehicle_out_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="status",
            field=models.CharField(choices=[("IN", "IN"), ("OUT", "OUT")], default="IN"),
            preserve_default=False,
        ),
    ]
