# Generated by Django 4.2.4 on 2023-09-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("milkmil", "0045_alter_vehicle_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="time",
            field=models.DateTimeField(),
        ),
    ]
