# Generated by Django 4.2.4 on 2023-09-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("milkmil", "0046_alter_vehicle_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleIDMap",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("vehicle_num", models.CharField(max_length=255)),
                ("rfid", models.CharField(max_length=255)),
            ],
        ),
    ]
