# Generated by Django 4.2.4 on 2023-09-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("milkmil", "0047_vehicleidmap"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicle",
            name="time",
        ),
        migrations.AddField(
            model_name="vehicle",
            name="in_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="out_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
