# Generated by Django 4.2.4 on 2023-08-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_usertypes"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.ManyToManyField(blank=True, null=True, to="users.usertypes"),
        ),
    ]
